packaging_format = 2

id = "glitchsoc"
name = "Glitch-Soc"
description.en = "Libre and federated social network, fork of Mastodon"
description.fr = "Réseau social libre et fédéré, scission de Mastodon"

version = "2023.07.29~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://glitch-soc.github.io/docs/"
code = "https://github.com/glitch-soc/mastodon"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "2G"
ram.build = "4G"
ram.runtime = "1G"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Visitors group is needed for federation."
    help.fr = "Le groupe visitors est nécessaire pour la fédération."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en_EN", "fr_FR"]
    default = "fr_FR"

[resources]
        [resources.sources.main]
        url = "https://github.com/glitch-soc/mastodon/archive/1cc3fcf7d089005e089cf523ea8cfc5193291693.tar.gz"
        sha256 = "b93374065ec3b81fe505452bd109f2c11e6bd01bfe3fa15fbc60e655076bfc8e"

        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.ports]
    web.default = 3000
    stream.default = 4000

    [resources.apt]
    packages = "imagemagick, ffmpeg, libpq-dev, libxml2-dev, libxslt1-dev, file, git-core, g++, libprotobuf-dev, protobuf-compiler, pkg-config, gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm6, libgdbm-dev, redis-server, redis-tools, postgresql, postgresql-contrib, libidn11-dev, libicu-dev, libjemalloc-dev, curl, apt-transport-https"

        [resources.apt.extras.yarn]
        repo = "deb https://dl.yarnpkg.com/debian/ stable main"
        key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
        packages = "yarn"

    [resources.database]
    type = "postgresql"
