test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.multi", "change_url"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9c7a5ae.name = "Upgrade from 2023.06.19~ynh1"
